"""

Revision ID: 1bf7308524c4
Revises: c18f4961b8dc
Create Date: 2026-02-25 09:27:18.387759

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '1bf7308524c4'
down_revision: str | Sequence[str] | None = 'c18f4961b8dc'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
