"""initial schema

Revision ID: 7a36eb36b555
Revises: 
Create Date: 2026-02-18 20:59:15.484654

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '7a36eb36b555'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('presence', sa.Enum('ONLINE', 'OFFLINE', name='agent_presence'), nullable=False),
    sa.Column('max_active_chats', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agents'))
    )
    op.create_table('faq_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('question', sa.String(length=300), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_faq_entries')),
    sa.UniqueConstraint('slug', name='uq_faq_slug')
    )
    op.create_table('conversations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('customer_session_id', sa.String(length=120), nullable=False),
    sa.Column('status', sa.Enum('AUTOMATED', 'AGENT', 'CLOSED', name='conversation_status'), nullable=False),
    sa.Column('assigned_agent_id', sa.Uuid(), nullable=True),
    sa.Column('requested_agent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_agent_id'], ['agents.id'], name=op.f('fk_conversations_assigned_agent_id_agents'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversations'))
    )
    op.create_index(op.f('ix_conversations_assigned_agent_id'), 'conversations', ['assigned_agent_id'], unique=False)
    op.create_index(op.f('ix_conversations_customer_session_id'), 'conversations', ['customer_session_id'], unique=False)
    op.create_index('ix_conversations_status', 'conversations', ['status'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('sender_type', sa.Enum('CUSTOMER', 'BOT', 'AGENT', 'SYSTEM', name='message_sender_type'), nullable=False),
    sa.Column('sender_agent_id', sa.Uuid(), nullable=True),
    sa.Column('kind', sa.Enum('TEXT', 'QUICK_REPLY', 'EVENT', name='message_kind'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_messages_conversation_id_conversations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_agent_id'], ['agents.id'], name=op.f('fk_messages_sender_agent_id_agents'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages'))
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index('ix_conversations_status', table_name='conversations')
    op.drop_index(op.f('ix_conversations_customer_session_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_assigned_agent_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_table('faq_entries')
    op.drop_table('agents')
    # ### end Alembic commands ###
